apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: observability-demo
spec:
  type: ClusterIP  
  selector:
    app: monitor   
  ports:
    - name: http
      port: 3000
      targetPort: 3000
