apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'node-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['app-svc:3000']