name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types: [ "completed" ]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: production   # opcional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          echo "IMAGE=lucasgoslar1/monitor" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "NAMESPACE=${{ secrets.K8S_NAMESPACE || 'observability-demo' }}" >> $GITHUB_OUTPUT

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        shell: powershell
        run: |
          $kubeDir = "$HOME\.kube"
          if (-not (Test-Path $kubeDir)) {
            New-Item -ItemType Directory -Path $kubeDir | Out-Null
          }

          $base64 = "${{ secrets.KUBE_CONFIG_DATA }}"
          $bytes  = [System.Convert]::FromBase64String($base64)
          $configPath = Join-Path $kubeDir "config"
          [System.IO.File]::WriteAllBytes($configPath, $bytes)

      - name: Create namespace if not exists
        shell: powershell
        run: |
          $ns = "${{ steps.vars.outputs.NAMESPACE }}"
          kubectl get ns $ns 2>$null
          if ($LASTEXITCODE -ne 0) {
            kubectl create ns $ns
          }


      # Aplica/garante os serviços/ingress/etc. estáticos (idempotente)
      - name: Apply base manifests (Service, Prometheus, Grafana, Nginx)
        run: |
          kubectl apply -f k8s/00-namespace.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/11-app-service.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/31-prometheus-deployment.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/42-grafana-deployment.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/21-nginx-deployment.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/22-nginx-service.yaml || true
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/30-prometheus-configmap.yaml || true

      # Aplica/garante o Deployment (se ainda não existir)
      - name: Apply app deployment (first time)
        run: |
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/deployment.yaml

      # Atualiza a imagem para a tag nova (idempotente)
      - name: Set image to new tag
        run: |
          kubectl set image deployment/monitor monitor=${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }} -n ${{ steps.vars.outputs.NAMESPACE }}

      - name: Wait rollout
        run: |
          kubectl rollout status deployment/monitor -n ${{ steps.vars.outputs.NAMESPACE }} --timeout=120s

      - name: Show services (debug)
        run: |
          kubectl get svc -n ${{ steps.vars.outputs.NAMESPACE }}
          kubectl get pods -o wide -n ${{ steps.vars.outputs.NAMESPACE }}
